repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint src
        language: python
        types: [python]

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check src
        language: python
        types: [python]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: python
        types: [python]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: python
        types: [python]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: python
        types: [python]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest --cov
        language: python
        types: [python]
        pass_filenames: false
