defaults:
  - _self_

# Model configuration
model:
  teacher:
    name: "vit_large_patch14_dinov2.lvd142m"
    args:
      global_pool: ""
  student:
    name: "dummy_model"
    args:
      in_channels: 3
      out_channels: 10

# Dataset configuration
data:
  name: "CIFAR10"
  batch_size: 32
  num_workers: 8
  dir_path: ../data
