defaults:
  - _self_

# Model configuration
model:
  teacher:
    name: "vit_large_patch14_dinov2.lvd142m"
    args:
      global_pool: ""
  student:
    name: "custom_vgg11"
    args:
      conv_layer_type: nn.Conv2D

# Dataset configuration
data:
  name: "CIFAR10"
  batch_size: 32
  num_workers: 8
  dir_path: ../data
